name: "Weather Message Sender"

on:
  push:
  schedule:
    - cron: "0 21 * * *"

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout codes"
        uses: actions/checkout@v1
        # 获取初始json格式的信息
      - name: "Get Origin Json File"
        run: bash ./weather.sh
        # 提取有效信息
        # 在这一步还要删除原本的result.js
      - name: "Extract Weather Condition"
        run: node translate.js
        # 发送短信
      - name: "Send Msg"
        run: node send.js
        # 记录日志
      - name: "Log Record"
        run: node log.js
