name: Weather Message Sender

on:
  push:
  schedule:
    - cron: "0 22 * * *"

jobs:
  sender:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout codes"
        uses: actions/checkout@v1
      - name: "Install Dependencies"
      - name: "Get Origin Json File"
        run: bash ./weather.sh
      - name: "Extract Weather Conditions"
        run: node ./translate
      - name: "Send Msg "
        run: node ./server/send.js
