name: Auto Sender Workflow

on:
  # push:
  #   branches:
  #     - master
  schedule:
    # 定时触发，北京时间6点
    - cron: "0 22 * * *"

jobs:
  sender:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: "Checkout codes"
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install Dependencies"
        run: |
          npm install
        env:
          CI: true

      - name: "Get Origin Json File"
        run: bash ./weather.sh

      - name: "Extract Weather Conditions"
        run: ts-node ./translate

      - name: "Send Msg"
        env:
          ID: ${{ secrets.SECRET_ID }}
          KEY: ${{ secrets.SECRET_KEY }}
          PHONE: ${{ secrets.PHONE_NUMBER }}
        run: |
          node_modules/.bin/cross-env SECRET_ID=$ID SECRET_KEY=$KEY PHONE=$PHONE ts-node ./server/send.ts
