name: Auto Sender Workflow

on:
  schedule:
    - cron: "0 22 * * *"

jobs:
  sender:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: "Checkout codes"
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm install
        env:
          CI: true

      - name: Get Origin Json File
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
        run: node_modules/.bin/cross-env APP_KEY=$APP_KEY node_modules/.bin/ts-node ./server/fetch.ts

      - name: Send Msg
        env:
          ID: ${{ secrets.SECRET_ID }}
          KEY: ${{ secrets.SECRET_KEY }}
          PHONE: ${{ secrets.PHONE_NUMBER }}
        run: |
          node_modules/.bin/cross-env SECRET_ID=$ID SECRET_KEY=$KEY PHONE=$PHONE node_modules/.bin/ts-node ./server/send.ts
